server:
  port: 8080
  error:
    include-stacktrace: never

api:
  kakao:
    host: https://dapi.kakao.com
    apiKey: KakaoAK b8aa43749a0c93b8e82456e0170e82db
  naver:
    host: https://openapi.naver.com
    clientId: k5AHGZws4IklEwSJF67Y
    clientSecret: 38L1XmxRYP

spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
